// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	icd10 "clinic-api/src/app/icd10"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Services is an autogenerated mock type for the Services type
type Services struct {
	mock.Mock
}

// FindICD10ByCode provides a mock function with given fields: code
func (_m *Services) FindICD10ByCode(code string) ([]icd10.Domain, error) {
	ret := _m.Called(code)

	var r0 []icd10.Domain
	if rf, ok := ret.Get(0).(func(string) []icd10.Domain); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]icd10.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServices creates a new instance of Services. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewServices(t testing.TB) *Services {
	mock := &Services{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
