// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	nurse "clinic-api/src/app/nurse"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Services is an autogenerated mock type for the Services type
type Services struct {
	mock.Mock
}

// AmendNurseByID provides a mock function with given fields: id, _a1
func (_m *Services) AmendNurseByID(id string, _a1 nurse.Domain) error {
	ret := _m.Called(id, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, nurse.Domain) error); ok {
		r0 = rf(id, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateNurse provides a mock function with given fields: _a0
func (_m *Services) CreateNurse(_a0 nurse.Domain) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(nurse.Domain) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(nurse.Domain) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllNurses provides a mock function with given fields:
func (_m *Services) GetAllNurses() ([]nurse.Domain, error) {
	ret := _m.Called()

	var r0 []nurse.Domain
	if rf, ok := ret.Get(0).(func() []nurse.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]nurse.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNurseByID provides a mock function with given fields: id
func (_m *Services) GetNurseByID(id string) (*nurse.Domain, error) {
	ret := _m.Called(id)

	var r0 *nurse.Domain
	if rf, ok := ret.Get(0).(func(string) *nurse.Domain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*nurse.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveNurseByID provides a mock function with given fields: id
func (_m *Services) RemoveNurseByID(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServices creates a new instance of Services. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewServices(t testing.TB) *Services {
	mock := &Services{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
