// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	account "clinic-api/src/app/account"

	mock "github.com/stretchr/testify/mock"
)

// Services is an autogenerated mock type for the Services type
type Services struct {
	mock.Mock
}

// AttemptLogin provides a mock function with given fields: domain
func (_m *Services) AttemptLogin(domain account.Domain) (*account.UserDataDomain, error) {
	ret := _m.Called(domain)

	var r0 *account.UserDataDomain
	if rf, ok := ret.Get(0).(func(account.Domain) *account.UserDataDomain); ok {
		r0 = rf(domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.UserDataDomain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(account.Domain) error); ok {
		r1 = rf(domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
