// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	polyclinic "clinic-api/src/app/polyclinic"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Services is an autogenerated mock type for the Services type
type Services struct {
	mock.Mock
}

// AmendPolyclinicByID provides a mock function with given fields: id, _a1
func (_m *Services) AmendPolyclinicByID(id int, _a1 polyclinic.Domain) error {
	ret := _m.Called(id, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, polyclinic.Domain) error); ok {
		r0 = rf(id, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePolyclinic provides a mock function with given fields: _a0
func (_m *Services) CreatePolyclinic(_a0 polyclinic.Domain) (int, error) {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(polyclinic.Domain) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(polyclinic.Domain) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPolyclinics provides a mock function with given fields:
func (_m *Services) GetAllPolyclinics() ([]polyclinic.Domain, error) {
	ret := _m.Called()

	var r0 []polyclinic.Domain
	if rf, ok := ret.Get(0).(func() []polyclinic.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]polyclinic.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPolyclinicsWithStats provides a mock function with given fields:
func (_m *Services) GetAllPolyclinicsWithStats() ([]polyclinic.Domain, error) {
	ret := _m.Called()

	var r0 []polyclinic.Domain
	if rf, ok := ret.Get(0).(func() []polyclinic.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]polyclinic.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPolyclinicByID provides a mock function with given fields: id
func (_m *Services) GetPolyclinicByID(id int) (*polyclinic.Domain, error) {
	ret := _m.Called(id)

	var r0 *polyclinic.Domain
	if rf, ok := ret.Get(0).(func(int) *polyclinic.Domain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*polyclinic.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemovePolyclinicByID provides a mock function with given fields: id
func (_m *Services) RemovePolyclinicByID(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServices creates a new instance of Services. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewServices(t testing.TB) *Services {
	mock := &Services{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
