name: "running build test"

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build program
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: build on go
        run: go build main.go
